name: Dispatchable Workflow

on:
    push:
    pull_request:
    workflow_dispatch:
        inputs:
            foo:
                description: Required field
                required: true
            bar:
                description: Optional field

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Show environment variables
              run: env

            - name: Show "github" context
              run: printf '%s' '${{ toJSON(github) }}' | jq .

            - name: Show bar
              run: printf '<%s>\n' '${{ github.event.inputs.bar }}'
