name: Foo

on:
  - push
  - pull_request

jobs:
  misc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Make a commit
        run: |
          touch newfile.txt
          git add newfile.txt
          git commit -m newfile
        env:
          GIT_AUTHOR_NAME: Me
          GIT_AUTHOR_EMAIL: me@example.com
          GIT_COMMITTER_NAME: Me
          GIT_COMMITTER_EMAIL: me@example.com
