name: Foo

on:
    - push

defaults:
    run:
        shell: bash

jobs:
    misc:
        #runs-on: windows-latest
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - run: git tag

            - run: |
                echo "::set-output name=action_fruit::"
              id: echo

            - run: echo Yes
              if: steps.echo.outputs.action_fruit != ''
