name: Foo

on:
    - push

defaults:
    run:
        shell: bash

jobs:
    misc:
        runs-on: windows-latest
        steps:
            - run: |
                echo "::set-output name=action_fruit::"
              id: echo

            - run: echo Yes
              if: steps.echo.outputs.action_fruit != ''
