name: Foo

on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  misc:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          #- ubuntu-latest
          #- macos-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run Python script
        run: python touch-bytes.py

      - name: Run Rust program
        run: cargo run -q -- ..
        working-directory: rust-test
