name: Foo

on:
    - push

defaults:
    run:
        shell: bash

jobs:
    misc:
        runs-on: windows-latest
        steps:
            - name: Find paths to some files
              run: |
                type git
                type timeout
