name: Foo

on:
    - push
    - pull_request

defaults:
    run:
        shell: bash

jobs:
    misc:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    #- windows-latest
                    - ubuntu-latest
                    #- macos-latest
        steps:
            - name: Checkout this repository
              uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - run: sudo apt-get update && sudo apt-get install -y tree

            - run: tree .git/refs

            - run: |
                echo "GITHUB_SHA=$GITHUB_SHA"
                echo "GITHUB_REF=$GITHUB_REF"

            - run: cat *.txt

            - name: Show GitHub context in its natural state
              run: printf '%s\n' ${{ github }}

#            - name: Send e-mail via Mailgun
#              uses: vineetchoudhary/mailgun-action@v1.0
#              with:
#                api-key: ${{ secrets.MAILGUN_API_KEY }}
#                domain: ${{ secrets.MAILGUN_DOMAIN }}
#                to: ${{ secrets.MAILGUN_RECIPIENT }}
#                from: Mailgun API <${{ secrets.MAILGUN_SENDER }}>
#                subject: Hello via Mailgun from ${{ github.workflow }}, run ${{ github.run_number }}!
#                body: |
#                    <p>This is an automatic e-mail notification from the ${{ github.workflow }} workflow on ${{ github.repository }}, run #${{ github.run_number }}.</p>
#
#                    <p>Here is a link to the workflow run: &lt;https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}&gt;</p>
#
#                    <p>This is a secret!  Did you know that ${{ secrets.MAILGUN_SECRET }}?</p>
#
#            - name: Send e-mail via SMTP
#              uses: dawidd6/action-send-mail@v2
#              with:
#                server_address: ${{ secrets.SMTP_HOST }}
#                server_port: ${{ secrets.SMTP_PORT }}
#                username: ${{ secrets.SMTP_USERNAME }}
#                password: ${{ secrets.SMTP_PASSWORD }}
#                from: Mailgun SMTP
#                to: ${{ secrets.MAILGUN_RECIPIENT }}
#                subject: Hello from ${{ github.workflow }}, run ${{ github.run_number }}!
#                body: |
#                    This is an automatic e-mail notification from the ${{ github.workflow }} workflow on ${{ github.repository }}, run #${{ github.run_number }}.
#
#                    Here is a link to the workflow run: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}>
#
#                    This is a secret!  Did you know that ${{ secrets.MAILGUN_SECRET }}?
