name: Foo

on:
    - push

defaults:
    run:
        shell: bash

jobs:
    misc:
        runs-on: ${{ matrix.os }}
        matrix:
            os:
                - windows-latest
                - ubuntu-latest
                - macos-latest
        steps:
            - run: uname -p
