name: Foo

on:
    - push
    - pull_request

defaults:
    run:
        shell: bash

jobs:
    misc:
        runs-on: ubuntu-latest
        #strategy:
        #    matrix:
        #        os:
        #            #- windows-latest
        #            - ubuntu-latest
        #            #- macos-latest
        steps:
            - name: Checkout this repository
              uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - run: sudo apt-get update && sudo apt-get install -y tree

            - run: tree .git/refs

            - run: |
                echo "GITHUB_SHA=$GITHUB_SHA"
                echo "GITHUB_REF=$GITHUB_REF"

            - run: cat *.txt

            - name: Show GitHub context
              run: printf '%s\n' '${{ toJson(github) }}'

            - name: Determine job URL
              run: |
                function api_call {
                  curl -fsSL \
                    -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    "$@"
                }
                api_call "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/jobs" | jq -r --arg job "${{ github.job }} (${{ matrix.os }})" '.jobs[] | select(.name == $job) | .html_url'

            - name: Test something
              run: echo "${{ join(matrix.*, ', ') }}"
