name: Foo

on:
    - push
    - pull_request

defaults:
    run:
        shell: bash

jobs:
    misc:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    #- windows-latest
                    - ubuntu-latest
                    #- macos-latest
        steps:
            - name: Checkout this repository
              uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - run: sudo apt-get update && sudo apt-get install -y tree

            - run: tree .git/refs

            - run: |
                echo "GITHUB_SHA=$GITHUB_SHA"
                echo "GITHUB_REF=$GITHUB_REF"

            - run: cat *.txt

            - name: Send e-mail
              uses: vineetchoudhary/mailgun-action@v1.0
              with:
                api-key: ${{ secrets.MAILGUN_API_KEY }}
                domain: ${{ secrets.MAILGUN_DOMAIN }}
                to: ${{ secrets.MAILGUN_RECIPIENT }}
                from: ${{ secrets.MAILGUN_SENDER }}
                subject: Hello from ${{ github.workflow }}, run ${{ github.run_number }}!
                body: |
                    This is an automatic e-mail notification from the ${{ github.workflow }} workflow on ${{ github.repository }}, run #${{ github.run_number }}.

                    Here is a link to the workflow run: <https://github.com/${{ github.repository }}/runs/${{ github.run_id }}>

                    This is a secret!  Did you know that ${{ secrets.MAILGUN_SECRET }}?
