name: Foo

on:
    - push
    - pull_request

defaults:
    run:
        shell: bash

jobs:
    misc:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    #- windows-latest
                    - ubuntu-latest
                    #- macos-latest
        steps:
            - name: Checkout this repository
              uses: actions/checkout@v2
              with:
                fetch-depth: 0

            #- run: sudo apt-get update && sudo apt-get install -y tree

            #- run: tree .git/refs

            #- run: |
            #    echo "GITHUB_SHA=$GITHUB_SHA"
            #    echo "GITHUB_REF=$GITHUB_REF"

            #- run: cat *.txt

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.6'

            - run: |
                type python
                type pip
                pip install twine
                type twine
