name: Foo

on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  misc:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          #- windows-latest
          - ubuntu-latest
          #- macos-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Make a commit
        run: |
          touch newfile.txt
          git add newfile.txt
          git commit -m newfile
        env:
          GIT_AUTHOR_NAME: Me
          GIT_AUTHOR_EMAIL: me@example.com
