name: Foo

on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  misc:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          #- ubuntu-latest
          #- macos-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pycryptodomex
        run: pip install pycryptodomex keyrings-alt

      - name: Test pycryptodomex
        #run: python -c "from Cryptodome.Protocol import KDF"
        run: python -c "from keyrings.alt.file import EncryptedKeyring"
