name: Test

on:
  push:
    braches:
      - master
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          #- windows-latest
          - ubuntu-latest
          #- macos-latest
    steps:
      #- name: Checkout this repository
      #  uses: actions/checkout@v4

      - name: Show secret
        run: perl -pl -e 's/(.)/$1 /g' <<<"$TEST_SECRET"
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
