name: Test

on:
  push:
    braches:
      - master
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          #- ubuntu-latest
          #- macos-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: pypy-3.10

      - run: pip install tox

      - run: pip list

      - run: tox -rvv -e py
