name: Test

on:
  push:
    braches:
      - master
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          #- windows-latest
          - ubuntu-latest
          #- macos-latest
    steps:
      #- name: Checkout this repository
      #  uses: actions/checkout@v4

      - name: Show envvars
        run: env
