name: Test

on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          #- windows-latest
          - ubuntu-latest
          #- macos-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Set an error message
        run: |
          echo '::error file=.github/workflows/test.yml,line=24,endLine=26,title=Hello!::This message came from here.'

      - name: Set a locationless error message
        run: |
          echo '::error title=Hello to no one!::Where did this come from?'
