name: Test

on:
  pull_request:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          #- windows-latest
          - ubuntu-latest
          #- macos-latest
    steps:
      #- name: Checkout this repository
      #  uses: actions/checkout@v6
      #  with:
      #    persist-credentials: false

      - name: Show envvars
        run: env
